# Generated by Django 2.0.1 on 2018-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180116_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.FloatField(default=4.0),
        ),
    ]
